import {Types} from 'mongoose';

// export interface IUser {
//   _id: Types.ObjectId | string;
//   userId: Types.ObjectId | string;
//   isMember: boolean;
//   sessionId: Types.ObjectId;
//   iat: number;
//   firstName: string;
//   lastName: string;
//   email: string;
//   status: string;
//   isVerified: boolean;
//   profileVerified: boolean;
//   freeUser: boolean;
//   statusOnline: string | boolean;
//   address: string;
//   postCode: string;
//   suburb: string;
//   state: string;
//   phonenumber: string;
//   profileImageUrl: string;
//   coverImageUrl: string;
//   role: RoleEnum;
//   roleCategory: roleCategoryEnum;
//   profileSummary: string;
//   profileDescription: string;
//   facebookUrl: string;
//   instagramUrl: string;
//   linkedinUrl: string;
//   whatsappUrl: string;
//   preferencelgbtq: boolean | null;
//   preferencemale: boolean | null;
//   preferencefemale: boolean | null;
//   preferencenopet: boolean | null;
//   preferencenonsmoker: boolean | null;
//   noPreferences: boolean | null;
//   personalityPetFriendly: boolean | null;
//   personalitySmoker: boolean | null;
//   hobbyCooking: boolean | null;
//   hobbyMusic: boolean | null;
//   hobbySports: boolean | null;
//   ABN: string;
//   policeCheck: string;
//   covid: string;
//   infectionControl: string;
//   childrenCheck: string;
//   referenceOne: string;
//   referenceTwo: string;
//   compareFeature: number;
//   cancelledJobs: number;
//   completedJobs: number;
//   totalReviews: number;
//   totalRatings: number;
//   jobPosted: number;
//   firebasetoken: string | null;
//   subscriptionId: string | null;
//   fullName?: string;
//   dateofbirth?: string;
//   gender?: genderEnum;
// }
